Feature/find prefixes
restechnica/semverbot pull request #84
Opened 2024-12-06 08:17 UTC by menathan

2024-12-06 08:20 UTC, menathan commented
Implements #82

2024-12-06 19:51 UTC, menathan commented
@shiouen, this PR will not include any breaking changes compared to previous PR #83 .
I added more explanation about this implementation in #82, and added also the appropriate tests.

2025-02-19 15:45 UTC, nogitting requested changes
First, let us agree on a number of points:

- _semver version[ing]_ is a tautology.
- One would expect SemVer-compliance from a tool called "SemverBot". At least, that should be the rule and, exceptions, if any, should be highlighted.
- Neither _v1.2.3_ nor _cool-prefix-1.2.3_ complies with the SemVer spec (as of 2.0.0). The difference is that the former is widely used for historical reasons and for other considerations (module versioning in Go, for instance).
- Semantic version =!= Package/Module version
- Semantic version =!= Tag name

Given the above, how to make _Semverbot_ monorepo-friendly?
It should be safe to say that, in a monorepo scenario, the tag prefix is the differentiator between the co-located components, since the suffix is reserved for pre-release and build metadata. That is, on the polyrepo side, you typically have one prefix, so all available tags are considered; on the monorepo side, you typically have multiple prefixes, so only related tags are considered.
Concretely, how to make this work as it should?
It should be as simple as replacing this line https://github.com/restechnica/semverbot/blob/0ee02a038aeadfeb607df21727e9b94eb16fa005/pkg/git/cli.go#L70 with the following
```go
return api.Commander.Output("git", "tag", "--sort=-version:refname", "--list", prefix + "[0-9]*")
```
No hardcoded 'v' nor any extra checks and whatnot. If polyrepo, this line is equivalent to the original one. and if monorepo, you only deal with the given prefix.
Now there are two ways:

- Update this function "in place".
- Add another function to the API, say `GetRelatedTags(prefix string)`, and depending on the `monorepo` flag (which you add support for), you call this function or the original `GetTags()`.

Either way, you will need to slightly update _pkg/git/cli.go_, _pkg/git/api.go_ and _pkg/versions/api.go_ (`GetVersion`, the main culprit), aside from their _internal/*_ counterparts, for tests.

2025-02-19 18:29 UTC, nogitting commented
Additional and final notes:

- _SemverBot_ relies on [blangsemver](https://github.com/blang/semver)'s `ParseTolerant` to parse versions, which, as the name implies, can tolerate versions that are not 100% SemVer-compliant (especially suffix-wise).
- The use of the suffix in the original code as an API parameter is superfluous for the most part.
- It is not a bad idea to make the `DefaultVersion` customizable instead of the constant `0.0.0`. Plus, implementation-wise, it is quite straightforward (by following the same pattern as for the other configuration parameters).
- _SemverBot_ is a good idea to help automate software versioning. However, (semantic) versioning is too complex to be fully and duly automated, especially when pre-releases come into play.

2025-03-21 13:34 UTC, menathan commented
Closing in favor of a new PR

2025-03-21 13:34 UTC, closed without merging